#!/usr/bin/env bash
for f in img/*.png; do
    echo "Processing $f file.."
    testName=${f%.*}
    testName=${testName##*/}
    hppName="$testName.h"
    ../../cmake-build-debug/tests/util/GenerateContours $f $testName > ../IsCircleTest/AutogeneratedImageTests/$hppName
done
