#!/usr/bin/env bash
for f in img/*.png; do
    testName=${f%.*}
    testName=${testName##*/}
    hppName="$testName.h"

    if [ -f ../tests/IsCircleTest/AutogeneratedImageTests/$hppName ];
    then
       echo "File already $hppName exists."
    else
       echo "Processing $hppName..."
       ../../cmake-build-debug/tests/util/GenerateContours $f $testName > ../tests/IsCircleTest/AutogeneratedImageTests/$hppName
    fi


done
