#This file requires all libraries to be installed, for more information see the readme

stages:
- validate
- test
- build

# Static Type Analysis
check:
  stage: validate
  script:
    - cppcheck . -I *.hpp > cppcheck.txt
  artifacts:
    paths:
    - cppcheck.txt

# Build the program
build:
  stage: build
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make OrangeBall

# run tests
test:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make RunUnitTests
    - tests/RunUnitTests
  artifacts:
    paths:
    - tests/log.txt