#This file requires all libraries to be installed, for more information see the readme

# Static Type Analysis
check:
  stage: test
  script:
    - cppcheck . -i cmake-build-debug/ -I *.hpp > cppcheck.txt
  artifacts:
    paths:
    - cppcheck.txt

# Build the program
build:
  stage: build
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make OrangeBall

# run tests
test:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make RunUnitTests
    - tests/RunUnitTests
  artifacts:
    paths:
    - tests/log.txt