#Thsi file requires all libraries to be installed, for more information see the readme
image: shell

build:
  stage: build
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make OrangeBall

# run tests
test:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make RunUnitTests
    - tests/RunUnitTests
  artifacts:
    paths:
    - tests/log.txt
