#include "gtest/gtest.h"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/opencv.hpp"
#include "opencv2/videoio.hpp"

#include "../CircleFinder.hpp"

#include "IsCircleTest/ToFewPoints.h"
#include "IsCircleTest/NoMatchingPoints.h"

//@TODO Check if their is a advantage by autogenerating tests
#if 0
    #include "IsCircleTest/AutogeneratedImageTests/BasicCircle.h"
    #include "IsCircleTest/AutogeneratedImageTests/CircleFragment.h"
    #include "IsCircleTest/AutogeneratedImageTests/HalfCircle.h"
    #include "IsCircleTest/AutogeneratedImageTests/HorizontalLine.h"
    #include "IsCircleTest/AutogeneratedImageTests/ImperfectCircle.h"
    #include "IsCircleTest/AutogeneratedImageTests/LineWithEdges.h"
    #include "IsCircleTest/AutogeneratedImageTests/LineWithLargeEdge.h"
    #include "IsCircleTest/AutogeneratedImageTests/LineWithSmallEdge.h"
    #include "IsCircleTest/AutogeneratedImageTests/RoundedLine.h"
    #include "IsCircleTest/AutogeneratedImageTests/SmallCircle.h"
    #include "IsCircleTest/AutogeneratedImageTests/Triangle.h"
    #include "IsCircleTest/AutogeneratedImageTests/VerticalLine.h"
#else
    #include "IsCircleTest/ImageTests/BasicCircle.h"
    #include "IsCircleTest/ImageTests/CircleFragment.h"
    #include "IsCircleTest/ImageTests/HalfCircle.h"
    #include "IsCircleTest/ImageTests/HorizontalLine.h"
    #include "IsCircleTest/ImageTests/ImperfectCircle.h"
    #include "IsCircleTest/ImageTests/LineWithEdges.h"
    #include "IsCircleTest/ImageTests/LineWithLargeEdge.h"
    #include "IsCircleTest/ImageTests/LineWithSmallEdge.h"
    #include "IsCircleTest/ImageTests/RoundedLine.h"
    #include "IsCircleTest/ImageTests/SmallCircle.h"
    #include "IsCircleTest/ImageTests/Triangle.h"
    #include "IsCircleTest/ImageTests/VerticalLine.h"
#endif

//@TODO CircleWithEdges generieren


int main(int argc, char **argv) {
      ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
