#include "gtest/gtest.h"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/opencv.hpp"
#include "opencv2/videoio.hpp"

#include "../CircleFinder.hpp"

#include "IsCircleTest/ToFewPoints.h"
#include "IsCircleTest/NoMatchingPoints.h"

#include "IsCircleTest/AutogeneratedImageTests/BasicCircle.h"
#include "IsCircleTest/AutogeneratedImageTests/CircleFragment.h"
#include "IsCircleTest/AutogeneratedImageTests/HalfCircle.h"
#include "IsCircleTest/AutogeneratedImageTests/HorizontalLine.h"
#include "IsCircleTest/AutogeneratedImageTests/ImperfectCircle.h"
#include "IsCircleTest/AutogeneratedImageTests/LineWithEdges.h"
#include "IsCircleTest/AutogeneratedImageTests/LineWithLargeEdge.h"
#include "IsCircleTest/AutogeneratedImageTests/LineWithSmallEdge.h"
#include "IsCircleTest/AutogeneratedImageTests/RoundedLine.h"
#include "IsCircleTest/AutogeneratedImageTests/SmallCircle.h"
#include "IsCircleTest/AutogeneratedImageTests/Triangle.h"
#include "IsCircleTest/AutogeneratedImageTests/VerticalLine.h"
#include "IsCircleTest/AutogeneratedImageTests/CircleWithEdges.h"
#include "IsCircleTest/AutogeneratedImageTests/DoubleLineHookFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/KeyFromKeyboardFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/LineWithHookFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/SpaceBarEdgeFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/TeaBottleContourFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/VerySmallCircle.h"
#include "IsCircleTest/AutogeneratedImageTests/DoubleDrawnLineFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/DoubleDrawnLineFromScreenshot2.h"
#include "IsCircleTest/AutogeneratedImageTests/DrawnLineFromScreenshot.h"
#include "IsCircleTest/AutogeneratedImageTests/DrawnLineFromScreenshot2.h"

int main(int argc, char **argv) {
      ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
